server:
  port: 8080
  context-path: /yuuki

spring.datasource:
  url: jdbc:mysql://127.0.0.1:3306/yuuki?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
  username: root
  password:
  driver-class-name:
